---
title: "DGS - Questionnaires"
author: "Rachael Martin"
date: "`r Sys.Date()`"
output:
  tufte::tufte_html: 
    toc: true
---

# Import

```{r}
library(haven)
library(data.table)
library(JWileymisc)

db <- as.data.table(read.csv("Pre-interview_numeric_withIDs.csv"))

s2db <- as.data.table(read.csv("Session2_main_numeric.csv"))

```

# Social connectedness scale - revised

```{r}
## reversal - now

db$SCS.R.2_3 <- as.numeric(db$SCS.R.2_3)
   
db[, SCS.R.2_3 := (5 - SCS.R.2_3)]

db$SCS.R.2_6 <- as.numeric(db$SCS.R.2_6)
   
db[, SCS.R.2_6 := (5 - SCS.R.2_6)]

db$SCS.R.2_7 <- as.numeric(db$SCS.R.2_7)
   
db[, SCS.R.2_7 := (5 - SCS.R.2_7)]

db$SCS.R.2_9 <- as.numeric(db$SCS.R.2_9)
   
db[, SCS.R.2_9 := (5 - SCS.R.2_9)]

db$SCS.R.2_11 <- as.numeric(db$SCS.R.2_11)
   
db[, SCS.R.2_11 := (5 - SCS.R.2_11)]

db$SCS.R.2_13 <- as.numeric(db$SCS.R.2_13)
   
db[, SCS.R.2_13 := (5 - SCS.R.2_13)]

db$SCS.R.2_15 <- as.numeric(db$SCS.R.2_15)
   
db[, SCS.R.2_15 := (5 - SCS.R.2_15)]

db$SCS.R.2_17 <- as.numeric(db$SCS.R.2_17)
   
db[, SCS.R.2_17 := (5 - SCS.R.2_17)]

db$SCS.R.2_18 <- as.numeric(db$SCS.R.2_18)
   
db[, SCS.R.2_18 := (5 - SCS.R.2_18)]

db$SCS.R.2_20 <- as.numeric(db$SCS.R.2_20)
   
db[, SCS.R.2_20 := (5 - SCS.R.2_20)]

## numeric for non reversed

db$SCS.R.2_1 <- as.numeric(db$SCS.R.2_1)
db$SCS.R.2_2 <- as.numeric(db$SCS.R.2_2)
db$SCS.R.2_4 <- as.numeric(db$SCS.R.2_4)
db$SCS.R.2_5 <- as.numeric(db$SCS.R.2_5)
db$SCS.R.2_8 <- as.numeric(db$SCS.R.2_8)
db$SCS.R.2_10 <- as.numeric(db$SCS.R.2_10)
db$SCS.R.2_12 <- as.numeric(db$SCS.R.2_12)
db$SCS.R.2_14 <- as.numeric(db$SCS.R.2_14)
db$SCS.R.2_16 <- as.numeric(db$SCS.R.2_16)
db$SCS.R.2_19 <- as.numeric(db$SCS.R.2_19)


## scoring - now


db[, SCSR2_Total := rowMeans(.SD, na.rm = TRUE)*20,
   .SDcols = c("SCS.R.2_1", "SCS.R.2_2", "SCS.R.2_3", "SCS.R.2_4", "SCS.R.2_5", "SCS.R.2_6", "SCS.R.2_7", "SCS.R.2_8", "SCS.R.2_9", "SCS.R.2_10", "SCS.R.2_11", "SCS.R.2_12", "SCS.R.2_13", "SCS.R.2_14", "SCS.R.2_15", "SCS.R.2_16", "SCS.R.2_17", "SCS.R.2_18", "SCS.R.2_19", "SCS.R.2_20")]

## reversal - puberty
db$SCS.R.1_3 <- as.numeric(db$SCS.R.1_3)
   
db[, SCS.R.1_3 := (5 - SCS.R.1_3)]

db$SCS.R.1_6 <- as.numeric(db$SCS.R.1_6)
   
db[, SCS.R.1_6 := (5 - SCS.R.1_6)]

db$SCS.R.1_7 <- as.numeric(db$SCS.R.1_7)
   
db[, SCS.R.1_7 := (5 - SCS.R.1_7)]

db$SCS.R.1_9 <- as.numeric(db$SCS.R.1_9)
   
db[, SCS.R.1_9 := (5 - SCS.R.1_9)]

db$SCS.R.1_11 <- as.numeric(db$SCS.R.1_11)
   
db[, SCS.R.1_11 := (5 - SCS.R.1_11)]

db$SCS.R.1_13 <- as.numeric(db$SCS.R.1_13)
   
db[, SCS.R.1_13 := (5 - SCS.R.1_13)]

db$SCS.R.1_15 <- as.numeric(db$SCS.R.1_15)
   
db[, SCS.R.1_15 := (5 - SCS.R.1_15)]

db$SCS.R.1_17 <- as.numeric(db$SCS.R.1_17)
   
db[, SCS.R.1_17 := (5 - SCS.R.1_17)]

db$SCS.R.1_18 <- as.numeric(db$SCS.R.1_18)
   
db[, SCS.R.1_18 := (5 - SCS.R.1_18)]

db$SCS.R.1_20 <- as.numeric(db$SCS.R.1_20)
   
db[, SCS.R.1_20 := (5 - SCS.R.1_20)]

## numeric for non reversed

db$SCS.R.1_1 <- as.numeric(db$SCS.R.1_1)
db$SCS.R.1_2 <- as.numeric(db$SCS.R.1_2)
db$SCS.R.1_4 <- as.numeric(db$SCS.R.1_4)
db$SCS.R.1_5 <- as.numeric(db$SCS.R.1_5)
db$SCS.R.1_8 <- as.numeric(db$SCS.R.1_8)
db$SCS.R.1_10 <- as.numeric(db$SCS.R.1_10)
db$SCS.R.1_12 <- as.numeric(db$SCS.R.1_12)
db$SCS.R.1_14 <- as.numeric(db$SCS.R.1_14)
db$SCS.R.1_16 <- as.numeric(db$SCS.R.1_16)
db$SCS.R.1_19 <- as.numeric(db$SCS.R.1_19)


## scoring - puberty


db[, SCSR1_Total := rowMeans(.SD, na.rm = TRUE)*20,
   .SDcols = c("SCS.R.1_1", "SCS.R.1_2", "SCS.R.1_3", "SCS.R.1_4", "SCS.R.1_5", "SCS.R.1_6", "SCS.R.1_7", "SCS.R.1_8", "SCS.R.1_9", "SCS.R.1_10", "SCS.R.1_11", "SCS.R.1_12", "SCS.R.1_13", "SCS.R.1_14", "SCS.R.1_15", "SCS.R.1_16", "SCS.R.1_17", "SCS.R.1_18", "SCS.R.1_19", "SCS.R.1_20")]

```

# Supportive School Environment Scale
```{r}
db$SSES.1 <- as.numeric(db$SSES.1)
db$SSES.2 <- as.numeric(db$SSES.1)
db$SSES.3 <- as.numeric(db$SSES.1)
db$SSES.4 <- as.numeric(db$SSES.1)
db$SSES.5 <- as.numeric(db$SSES.1)
db$SSES.6 <- as.numeric(db$SSES.1)
db$SSES.7 <- as.numeric(db$SSES.1)
```

# Supportive School GLBT

```{r}
db$SSLBT.1 <- as.numeric(db$SSLBT.1)
db$SSLBT.2 <- as.numeric(db$SSLBT.1)
db$SSLBT.3 <- as.numeric(db$SSLBT.1)
db$SSLBT.4 <- as.numeric(db$SSLBT.1)
```


# DASS-21
```{r}
#numeric

s2db$DASS.21_Current_1 <- as.numeric(s2db$DASS.21_Current_1)
s2db[, DASS.21_Current_1 := (DASS.21_Current_1 - 1)]

s2db$DASS.21_Current_2 <- as.numeric(s2db$DASS.21_Current_2)
s2db[, DASS.21_Current_2 := (DASS.21_Current_2 - 1)]

s2db$DASS.21_Current_3 <- as.numeric(s2db$DASS.21_Current_3)
s2db[, DASS.21_Current_3 := (DASS.21_Current_3 - 1)]

s2db$DASS.21_Current_4 <- as.numeric(s2db$DASS.21_Current_4)
s2db[, DASS.21_Current_4 := (DASS.21_Current_4 - 1)]


s2db$DASS.21_Current_5 <- as.numeric(s2db$DASS.21_Current_5)
s2db[, DASS.21_Current_5 := (DASS.21_Current_5 - 1)]


s2db$DASS.21_Current_6 <- as.numeric(s2db$DASS.21_Current_6)
s2db[, DASS.21_Current_6 := (DASS.21_Current_6 - 1)]


s2db$DASS.21_Current_7 <- as.numeric(s2db$DASS.21_Current_7)
s2db[, DASS.21_Current_7 := (DASS.21_Current_7 - 1)]

s2db$DASS.21_Current_8 <- as.numeric(s2db$DASS.21_Current_8)
s2db[, DASS.21_Current_8 := (DASS.21_Current_8 - 1)]


s2db$DASS.21_Current_9 <- as.numeric(s2db$DASS.21_Current_9)
s2db[, DASS.21_Current_9 := (DASS.21_Current_9 - 1)]

s2db$DASS.21_Current_10 <- as.numeric(s2db$DASS.21_Current_10)
s2db[, DASS.21_Current_10 := (DASS.21_Current_10 - 1)]

s2db$DASS.21_Current_11 <- as.numeric(s2db$DASS.21_Current_11)
s2db[, DASS.21_Current_11 := (DASS.21_Current_11 - 1)]

s2db$DASS.21_Current_12 <- as.numeric(s2db$DASS.21_Current_12)
s2db[, DASS.21_Current_12 := (DASS.21_Current_12 - 1)]

s2db$DASS.21_Current_13 <- as.numeric(s2db$DASS.21_Current_13)
s2db[, DASS.21_Current_13 := (DASS.21_Current_13 - 1)]

s2db$DASS.21_Current_14 <- as.numeric(s2db$DASS.21_Current_14)
s2db[, DASS.21_Current_14 := (DASS.21_Current_14 - 1)]

s2db$DASS.21_Current_15 <- as.numeric(s2db$DASS.21_Current_15)
s2db[, DASS.21_Current_15 := (DASS.21_Current_15 - 1)]

s2db$DASS.21_Current_16 <- as.numeric(s2db$DASS.21_Current_16)
s2db[, DASS.21_Current_16 := (DASS.21_Current_16 - 1)]

s2db$DASS.21_Current_17 <- as.numeric(s2db$DASS.21_Current_17)
s2db[, DASS.21_Current_17 := (DASS.21_Current_17 - 1)]

s2db$DASS.21_Current_18 <- as.numeric(s2db$DASS.21_Current_18)
s2db[, DASS.21_Current_18 := (DASS.21_Current_18 - 1)]

s2db$DASS.21_Current_19 <- as.numeric(s2db$DASS.21_Current_19)
s2db[, DASS.21_Current_19 := (DASS.21_Current_19 - 1)]

s2db$DASS.21_Current_20 <- as.numeric(s2db$DASS.21_Current_20)
s2db[, DASS.21_Current_20 := (DASS.21_Current_20 - 1)]

s2db$DASS.21_Current_21 <- as.numeric(s2db$DASS.21_Current_21)
s2db[, DASS.21_Current_21 := (DASS.21_Current_21 - 1)]

s2db$DASS.21_Puberty_1 <- as.numeric(s2db$DASS.21_Puberty_1)
s2db[, DASS.21_Puberty_1 := (DASS.21_Puberty_1 - 1)]

s2db$DASS.21_Puberty_2 <- as.numeric(s2db$DASS.21_Puberty_2)
s2db[, DASS.21_Puberty_2 := (DASS.21_Puberty_2 - 1)]

s2db$DASS.21_Puberty_3 <- as.numeric(s2db$DASS.21_Puberty_3)
s2db[, DASS.21_Puberty_3 := (DASS.21_Puberty_3 - 1)]

s2db$DASS.21_Puberty_4 <- as.numeric(s2db$DASS.21_Puberty_4)
s2db[, DASS.21_Puberty_4 := (DASS.21_Puberty_4 - 1)]


s2db$DASS.21_Puberty_5 <- as.numeric(s2db$DASS.21_Puberty_5)
s2db[, DASS.21_Puberty_5 := (DASS.21_Puberty_5 - 1)]


s2db$DASS.21_Puberty_6 <- as.numeric(s2db$DASS.21_Puberty_6)
s2db[, DASS.21_Puberty_6 := (DASS.21_Puberty_6 - 1)]


s2db$DASS.21_Puberty_7 <- as.numeric(s2db$DASS.21_Puberty_7)
s2db[, DASS.21_Puberty_7 := (DASS.21_Puberty_7 - 1)]

s2db$DASS.21_Puberty_8 <- as.numeric(s2db$DASS.21_Puberty_8)
s2db[, DASS.21_Puberty_8 := (DASS.21_Puberty_8 - 1)]


s2db$DASS.21_Puberty_9 <- as.numeric(s2db$DASS.21_Puberty_9)
s2db[, DASS.21_Puberty_9 := (DASS.21_Puberty_9 - 1)]

s2db$DASS.21_Puberty_10 <- as.numeric(s2db$DASS.21_Puberty_10)
s2db[, DASS.21_Puberty_10 := (DASS.21_Puberty_10 - 1)]

s2db$DASS.21_Puberty_11 <- as.numeric(s2db$DASS.21_Puberty_11)
s2db[, DASS.21_Puberty_11 := (DASS.21_Puberty_11 - 1)]

s2db$DASS.21_Puberty_12 <- as.numeric(s2db$DASS.21_Puberty_12)
s2db[, DASS.21_Puberty_12 := (DASS.21_Puberty_12 - 1)]

s2db$DASS.21_Puberty_13 <- as.numeric(s2db$DASS.21_Puberty_13)
s2db[, DASS.21_Puberty_13 := (DASS.21_Puberty_13 - 1)]

s2db$DASS.21_Puberty_14 <- as.numeric(s2db$DASS.21_Puberty_14)
s2db[, DASS.21_Puberty_14 := (DASS.21_Puberty_14 - 1)]

s2db$DASS.21_Puberty_15 <- as.numeric(s2db$DASS.21_Puberty_15)
s2db[, DASS.21_Puberty_15 := (DASS.21_Puberty_15 - 1)]

s2db$DASS.21_Puberty_16 <- as.numeric(s2db$DASS.21_Puberty_16)
s2db[, DASS.21_Puberty_16 := (DASS.21_Puberty_16 - 1)]

s2db$DASS.21_Puberty_17 <- as.numeric(s2db$DASS.21_Puberty_17)
s2db[, DASS.21_Puberty_17 := (DASS.21_Puberty_17 - 1)]

s2db$DASS.21_Puberty_18 <- as.numeric(s2db$DASS.21_Puberty_18)
s2db[, DASS.21_Puberty_18 := (DASS.21_Puberty_18 - 1)]

s2db$DASS.21_Puberty_19 <- as.numeric(s2db$DASS.21_Puberty_19)
s2db[, DASS.21_Puberty_19 := (DASS.21_Puberty_19 - 1)]

s2db$DASS.21_Puberty_20 <- as.numeric(s2db$DASS.21_Puberty_20)
s2db[, DASS.21_Puberty_20 := (DASS.21_Puberty_20 - 1)]

s2db$DASS.21_Puberty_21 <- as.numeric(s2db$DASS.21_Puberty_21)
s2db[, DASS.21_Puberty_21 := (DASS.21_Puberty_21 - 1)]
## depression - now
s2db[, DASS21_CDepression1 := rowMeans(.SD, na.rm = TRUE)*7,
     .SDcols = c("DASS.21_Current_3", "DASS.21_Current_5", "DASS.21_Current_10", "DASS.21_Current_13", "DASS.21_Current_16", "DASS.21_Current_17", "DASS.21_Current_21")]

s2db[, DASS21_CDepressionFINAL := DASS21_CDepression1*2]
## anxiety - now
s2db[, DASS21_CAnxiety1 := rowMeans(.SD, na.rm = TRUE)*7,
     .SDcols = c("DASS.21_Current_2", "DASS.21_Current_4", "DASS.21_Current_7", "DASS.21_Current_9", "DASS.21_Current_15", "DASS.21_Current_19", "DASS.21_Current_20")]

s2db[, DASS21_CAnxietyFINAL := DASS21_CAnxiety1*2]

## stress - now
s2db[, DASS21_CStress1 := rowMeans(.SD, na.rm = TRUE)*7,
     .SDcols = c("DASS.21_Current_1", "DASS.21_Current_6", "DASS.21_Current_8", "DASS.21_Current_11", "DASS.21_Current_12", "DASS.21_Current_14", "DASS.21_Current_18")]

s2db[, DASS21_CStressFINAL := DASS21_CStress1*2]

## total - now
s2db[, DASS21_CTotal := DASS21_CStressFINAL + DASS21_CAnxietyFINAL + DASS21_CDepressionFINAL]

## depression - puberty
s2db[, DASS21_PDepression1 := rowMeans(.SD, na.rm = TRUE)*7,
     .SDcols = c("DASS.21_Puberty_3", "DASS.21_Puberty_5", "DASS.21_Puberty_10", "DASS.21_Puberty_13", "DASS.21_Puberty_16", "DASS.21_Puberty_17", "DASS.21_Puberty_21")]

s2db[, DASS21_PDepressionFINAL := DASS21_PDepression1*2]
## anxiety - puberty
s2db[, DASS21_PAnxiety1 := rowMeans(.SD, na.rm = TRUE)*7,
     .SDcols = c("DASS.21_Puberty_2", "DASS.21_Puberty_4", "DASS.21_Puberty_7", "DASS.21_Puberty_9", "DASS.21_Puberty_15", "DASS.21_Puberty_19", "DASS.21_Puberty_20")]

s2db[, DASS21_PAnxietyFINAL := DASS21_PAnxiety1*2]

## stress - puberty
s2db[, DASS21_PStress1 := rowMeans(.SD, na.rm = TRUE)*7,
     .SDcols = c("DASS.21_Puberty_1", "DASS.21_Puberty_6", "DASS.21_Puberty_8", "DASS.21_Puberty_11", "DASS.21_Puberty_12", "DASS.21_Puberty_14", "DASS.21_Puberty_18")]

s2db[, DASS21_PStressFINAL := DASS21_PStress1*2]

## total - puberty
s2db[, DASS21_PTotal := DASS21_PStressFINAL + DASS21_PAnxietyFINAL + DASS21_PDepressionFINAL]
```
# MSPSS
```{r}
## puberty

db$MSPSS.1.1_1 <- as.numeric(db$MSPSS.1.1_1)

db$MSPSS.1.1_2 <- as.numeric(db$MSPSS.1.1_2)

db$MSPSS.1.1_3 <- as.numeric(db$MSPSS.1.1_3)

db$MSPSS.1.1_4 <- as.numeric(db$MSPSS.1.1_4)

db$MSPSS.1.1_5 <- as.numeric(db$MSPSS.1.1_5)

db$MSPSS.1.1_6 <- as.numeric(db$MSPSS.1.1_6)

db$MSPSS.1.1_7 <- as.numeric(db$MSPSS.1.1_7)

## now

db$MSPSS.1.2_1 <- as.numeric(db$MSPSS.1.2_1)

db$MSPSS.1.2_2 <- as.numeric(db$MSPSS.1.2_2)

db$MSPSS.1.2_3 <- as.numeric(db$MSPSS.1.2_3)

db$MSPSS.1.2_4 <- as.numeric(db$MSPSS.1.2_4)

db$MSPSS.1.2_5 <- as.numeric(db$MSPSS.1.2_5)

db$MSPSS.1.2_6 <- as.numeric(db$MSPSS.1.2_6)

db$MSPSS.1.2_7 <- as.numeric(db$MSPSS.1.2_7)

## puberty

db$MSPSS.2.1_1 <- as.numeric(db$MSPSS.2.1_1)

db$MSPSS.2.1_2 <- as.numeric(db$MSPSS.2.1_2)

db$MSPSS.2.1_3 <- as.numeric(db$MSPSS.2.1_3)

db$MSPSS.2.1_4 <- as.numeric(db$MSPSS.2.1_4)

db$MSPSS.2.1_5 <- as.numeric(db$MSPSS.2.1_5)

db$MSPSS.2.1_6 <- as.numeric(db$MSPSS.2.1_6)

## now

db$MSPSS.2.2_1 <- as.numeric(db$MSPSS.2.2_1)

db$MSPSS.2.2_2 <- as.numeric(db$MSPSS.2.2_2)

db$MSPSS.2.2_3 <- as.numeric(db$MSPSS.2.2_3)

db$MSPSS.2.2_4 <- as.numeric(db$MSPSS.2.2_4)

db$MSPSS.2.2_5 <- as.numeric(db$MSPSS.2.2_5)

db$MSPSS.2.2_6 <- as.numeric(db$MSPSS.2.2_6)

## scoring puberty

## significant other subscale
db[, MSPSS_P_SO := rowMeans(.SD, na.rm = TRUE), .SDcols = c("MSPSS.1.1_1", "MSPSS.1.1_2", "MSPSS.1.1_5", "MSPSS.2.1_4")]

## family subscale
db[, MSPSS_P_Fa := rowMeans(.SD, na.rm = TRUE), .SDcols = c("MSPSS.1.1_3", "MSPSS.1.1_4", "MSPSS.2.1_2", "MSPSS.2.1_5")]

## friends subscale
db[, MSPSS_P_Fr := rowMeans(.SD, na.rm = TRUE), .SDcols = c("MSPSS.1.1_6", "MSPSS.2.1_1", "MSPSS.2.1_3", "MSPSS.2.1_6")]

## total
db[, MSPSS_P_TOTAL := rowMeans(.SD, na.rm = TRUE), .SDcols = c("MSPSS.1.1_1", "MSPSS.1.1_2", "MSPSS.1.1_3", "MSPSS.1.1_4", "MSPSS.1.1_5", "MSPSS.1.1_6", "MSPSS.2.1_1", "MSPSS.2.1_2", "MSPSS.2.1_3", "MSPSS.2.1_4", "MSPSS.2.1_5", "MSPSS.2.1_6")]

## scoring now

## significant other subscale
db[, MSPSS_C_SO := rowMeans(.SD, na.rm = TRUE), .SDcols = c("MSPSS.1.2_1", "MSPSS.1.2_2", "MSPSS.1.2_5", "MSPSS.1.2_4")]

## family subscale
db[, MSPSS_C_Fa := rowMeans(.SD, na.rm = TRUE), .SDcols = c("MSPSS.1.2_3", "MSPSS.1.2_4", "MSPSS.2.2_2", "MSPSS.2.2_5")]

## friends subscale
db[, MSPSS_C_Fr := rowMeans(.SD, na.rm = TRUE), .SDcols = c("MSPSS.1.2_6", "MSPSS.2.2_1", "MSPSS.2.2_3", "MSPSS.2.2_6")]

## total
db[, MSPSS_C_TOTAL := rowMeans(.SD, na.rm = TRUE), .SDcols = c("MSPSS.1.2_1", "MSPSS.1.2_2", "MSPSS.1.2_3", "MSPSS.1.2_4", "MSPSS.1.2_5", "MSPSS.1.2_6", "MSPSS.2.2_1", "MSPSS.2.2_2", "MSPSS.2.2_3", "MSPSS.2.2_4", "MSPSS.2.2_5", "MSPSS.2.2_6")]

```
# FCS
```{r}
db$FCS.1.1_1 <- as.numeric(db$FCS.1.1_1)
db$FCS.1.2_1 <- as.numeric(db$FCS.1.2_1)
db$FCS.2.1_1 <- as.numeric(db$FCS.2.1_1)
db$FCS.2.1_2 <- as.numeric(db$FCS.2.1_2)
db$FCS.2.1_3 <- as.numeric(db$FCS.2.1_3)
db$FCS.2.1_4 <- as.numeric(db$FCS.2.1_4)
db$FCS.3.1_1 <- as.numeric(db$FCS.3.1_1)
db$FCS.3.1_2 <- as.numeric(db$FCS.3.1_2)
db$FCS.3.1_3 <- as.numeric(db$FCS.3.1_3)
db$FCS.3.1_4 <- as.numeric(db$FCS.3.1_4)
db$FCS.3.1_5 <- as.numeric(db$FCS.3.1_5)
```

# EDS
```{r}
db[, c("EDS.1_1", "EDS.1_2", "EDS.1_3", "EDS.1_4", "EDS.1_5", "EDS.1_6", "EDS.1_7", "EDS.1_8", "EDS.1_9")] <- lapply(db[, c("EDS.1_1", "EDS.1_2", "EDS.1_3", "EDS.1_4", "EDS.1_5", "EDS.1_6", "EDS.1_7", "EDS.1_8", "EDS.1_9")],as.numeric)

```

